replicaCount: 1
name: byor-voting-web-app
namespace: byor
image: 
    repository: byoritaly/byor-voting-web-app
    tag: latest
    pullPolicy: IfNotPresent

containerPort: 80
service: 
    port: 80
    nodePort: 30080
    type: NodePort
    backendServiceUrl: 'http://localhost:30090/'
    radarServiceUrl: 'https://radar.thoughtworks.com/'
    replicaCount: 1